language: php

php:
  - '7.4.16'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
